# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebDriverIO CI

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 9 * * MON-FRI'

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - run: npm install

      - run: npm run test
      
      - uses: actions/upload-artifact@master
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: ${{github.workspace}}/reports/allure-results
          retention-days: 20
                    
  generate-report:
     runs-on: ubuntu-latest
     needs: run-tests
     if: always()
     
     steps:
      - uses: actions/checkout@v2
      
      - name: Download Artifact
        if: always()
        continue-on-error: true
        uses: actions/download-artifact@master
        with:
          name: allure-results
          path: ./allure-results
         
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5
          
      - uses: actions/upload-artifact@master
        if: always()
        continue-on-error: true
        with:
          name: allure-report
          path: ${{github.workspace}}/allure-report
          retention-days: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
